### ISSUE TITLE
Issue with wildcard character '*' in TC Artifact Dependencies --> Artifacts Paths

### ISSUE THREAD

**Issue by darcywong00** [chrisvire/BuildUpdate#10]
I had an existing artifact dependency on TC that used a wildcard like
```
*.dll=>lib/DebugMono
*.config=>lib/DebugMono
```
When I ran buildupdate, I got the following error:
````
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!': 404 Resource Not Found (RestClient::ResourceNotFound)
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in
`process_result'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in
`block in transmit'
        from C:/Ruby193/lib/ruby/1.9.1/net/http.rb:746:in `start'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in 
`transmit'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/rest-client-1.6.7/lib/restclient/resource.rb:51:in
`get'
        from C:/src/BuildUpdate/buildupdate.rb:242:in `block (2 levels) in <main>'
        from C:/src/BuildUpdate/buildupdate.rb:233:in `each'
        from C:/src/BuildUpdate/buildupdate.rb:233:in `block in <main>'
        from C:/src/BuildUpdate/buildupdate.rb:232:in `each'
        from C:/src/BuildUpdate/buildupdate.rb:232:in `<main>'
````
If a modify the artifact dependencies to use specific names
````
icu.net.dll=>lib/DebugMono
icu.net.dll.config=>lib/DebugMono
````
The buildupdate script runs fine.  Some older project configurations still reference dependencies with the wildcard, so I wondered if something in buildupdate got changed.

**Comment by chrisvire** [comment]
It would help to fix if you give me an example.

**Comment by darcywong00** [comment]
I think I was previously getting this on id=buildType:bt454, but I can't duplicate it now.
I'll close this.
